# Generated by Django 3.1.7 on 2021-04-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_item_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='specification',
            field=models.TextField(blank=True),
        ),
    ]
