# Generated by Django 3.1.7 on 2021-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_item_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_image1',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_image2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_image3',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
