# Generated by Django 3.1.7 on 2021-04-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210403_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sub_image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sub_image3',
        ),
    ]
