# Generated by Django 3.1.7 on 2021-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('review', models.TextField(blank=True)),
                ('rating', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=None, max_length=200)),
            ],
        ),
    ]
