# Generated by Django 3.1.7 on 2021-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slog',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
