# Generated by Django 3.1.7 on 2021-04-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
