# Generated by Django 3.1.7 on 2021-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210502_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='all_total',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CartTotal',
        ),
    ]
