# Generated by Django 3.1.7 on 2021-05-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_cart_all_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='all_total',
        ),
    ]
