# Generated by Django 3.1.7 on 2021-05-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_carttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttotal',
            name='all_total',
            field=models.IntegerField(default=0),
        ),
    ]
