# Generated by Django 3.1.7 on 2021-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_carttotal_all_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttotal',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
