# Generated by Django 3.1.7 on 2021-06-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_carttotal_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartTotal',
        ),
    ]
