# Generated by Django 3.1.7 on 2021-06-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_cart_all_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('all_total', models.IntegerField(default=0)),
                ('checkout', models.BooleanField(default=False)),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
            ],
        ),
    ]
