# Generated by Django 3.1.7 on 2021-06-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='fname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='checkout',
            name='lname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
