# Generated by Django 3.1.7 on 2021-06-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20210610_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
