# Generated by Django 3.1.7 on 2021-06-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_delete_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('fname', models.CharField(blank=True, max_length=200)),
                ('lname', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('mobile_no', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('last', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.cart')),
            ],
        ),
    ]
