# Generated by Django 3.1.7 on 2021-07-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='last',
        ),
    ]
