# Generated by Django 3.1.7 on 2021-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_remove_checkout_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_cost',
            field=models.IntegerField(default=100),
        ),
    ]
