# Generated by Django 3.1.7 on 2021-07-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20210724_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
