# Generated by Django 3.1.7 on 2021-07-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20210724_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_cost',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
