# Generated by Django 3.1.7 on 2021-08-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20210803_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_cost',
        ),
    ]
