# Generated by Django 3.1.7 on 2021-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_remove_cart_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='fname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='lname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
