# Generated by Django 3.1.7 on 2021-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_checkout_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout',
            field=models.BooleanField(default=True),
        ),
    ]
