# Generated by Django 3.1.7 on 2021-08-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20210803_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='checkout',
        ),
    ]
